### ISSUE TITLE
Game slowdown and icon missing on world map 

### ISSUE THREAD

**Issue by MissPotato** [neronix17/-O21-Goblins#1]
Thing spammed in console: https://pastebin.com/c7Yv4vwr
Full logs: https://pastebin.com/yc5f6Jra
Picture of error: https://i.imgur.com/HQCQPdb.jpg

When making a crashlanded base selecting the world tab to view the world causes the game to slow down and the base indicator doesn't render. Zooming in causes the base to be a red X. This doesn't happen with the mod loaded and using the default crashlanded option.

**Comment by neronix17** [comment]
Already aware of the broken texture path, just haven't had time to fix it due to the holidays. In future don't bother with a log unless it's from using Ctrl+F12, the vanilla one is just worthless most of the time as it leaves out the actual useful info.

**Comment by MissPotato** [comment]
Alright, thank you for letting me know! And all good, just wanted to let ya' know. 😄

**Comment by neronix17** [comment]
Fixed in the latest patch now.
